export const projectConstantLocal = {
  PERPAGING_LIMIT: 5,
  EMAIL_LABEL: 'Email',
  PASSWORD_LABEL: 'Password',
  EMAIL_REQUIRED: 'Email is required',
  PASSWORD_REQUIRED: 'Password is required',
  EMAIL_VALID_MSG: 'Email must be a valid email address',
  PASS_VALID_MSG: 'Password must be at least 6 characters',
  REGISTER_BTN: 'Register',
  SNACKBAR_TIMEOUT_DELAY: 4100,
  SUCCESSFULL_LOGiN_MSG: 'You have successfully logged in',
  EMAIL_NOT_EXIST: 'email address does not exists.',
  LOG_IN_BTN: 'LOG IN',
  PASS_LENGTH_VALIDATION: 'Your password should be greater then seven digit',
  EMAIL_PASS_VALIDATION_MSG: 'Please enter correct email id or password',
  TOTAL_PAGE_LIMIT: 10,
  ORGANIZATION_MSG_PLACEHOLDER: 'Enter organization name',
  ORGANIZATION_COUNTRY_MSG_PLACEHOLDER: 'Select country name',
  ORGANIZATION_STATE_MSG_PLACEHOLDER: 'Select state name',
  ORGANIZATION_MSG_VALIDATION: 'Please enter organization name',
  ORGANIZATION_COUNTRY_MSG_VALIDATION: 'Please select country name',
  ORGANIZATION_STATE_MSG_VALIDATION: 'Please enter state name',
  ORGANIZATION_COUNTRY_CODE: 'Country code',
  ORGANIZATION_COUNTRY_CODE_VALIDATION: 'Select country code',
  SUBSCRIPTION_TABLE_ACTION_VALIDATION:
    'Please select any one checkbox to perform',
  TABLE_ACTION_VALIDATION: 'Please select any one checkbox to perform',
  STATUS_SELECT: 'Please select atleast one status',
  ENABLE_STATE: 'Please select country first',
  SEARCH_ERROR: 'Sorry you have no data',
  SEARCHERROR: 'Please give some valid input to search',
};
